version: '3.1'

services:
  mongo:
    container_name: mongo_bar
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo:/data/db

  mongo-express:
    container_name: mongo-express_bar
    image: mongo-express
    restart: always
    ports:
      - 27031:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://admin:root@mongo:27017/

volumes:
  mongo:
    name: mongo_bar
